---

- name: Get wazuh apt repo gpg key
  ansible.builtin.get_url:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    dest: /etc/apt/trusted.gpg.d/wazuh.asc
    mode: '0644'
  become: true

- name: Add wazuh apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/wazuh.asc] https://packages.wazuh.com/4.x/apt/ stable main"
    filename: wazuh #".list" gets appended automatically
    state: present
    update_cache: true
  become: true

- name: Configure wazuh manager host
  ansible.builtin.shell: 'WAZUH_MANAGER="{{ potos_wazuh_agent_manager_ip }}"'
  changed_when: false
  become: true

- name: Install wazuh agent
  ansible.builtin.apt:
    name: wazuh-agent
    update_cache: true
    cache_valid_time: 604800
  become: true
  notify: Restart wazuh-agent

#- name: Disable updates for wazuh-agent
#  ansible.builtin.shell: echo "wazuh-agent hold" | dpkg --set-selections
#  changed_when: false
#  become: true
